### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by akeinhell** [akeinhell/redfoxbot#3]
```
[2017-03-25 15:10:34] production.ALERT: /var/www/telegram/releases/2/vendor/telegram-bot/api/src/BotApi.phpBad Request ["
#0 /var/www/telegram/releases/2/vendor/telegram-bot/api/src/BotApi.php(241): TelegramBot\\Api\\BotApi::curlValidate(Resource id #20)\n
#1 /var/www/telegram/releases/2/vendor/telegram-bot/api/src/BotApi.php(210): TelegramBot\\Api\\BotApi->executeCurl(Array)\n
#2 /var/www/telegram/releases/2/vendor/telegram-bot/api/src/BotApi.php(316): TelegramBot\\Api\\BotApi->call('sendMessage', Array)\n
#3 /var/www/telegram/releases/2/app/Http/Controllers/TelegramController.php(445): TelegramBot\\Api\\BotApi->sendMessage(-1001092919844, '\\xD0\\x9D\\xD0\\xB8\\xD0\\xB6\\xD0\\xB5 \\xD0\\xBF\\xD1\\x80\\xD0\\xB8...', 'HTML', true, NULL, NULL)\n
#4 /var/www/telegram/releases/2/app/Http/Controllers/TelegramController.php(213): App\\Http\\Controllers\\TelegramController->sendMessage(-1001092919844, '\\xD0\\x9D\\xD0\\xB8\\xD0\\xB6\\xD0\\xB5 \\xD0\\xBF\\xD1\\x80\\xD0\\xB8...')\n
#5 /var/www/telegram/releases/2/app/Http/Controllers/TelegramController.php(152): App\\Http\\Controllers\\TelegramController->tryParseEmoji(Object(TelegramBot\\Api\\Types\\Message))\n
#6 /var/www/telegram/releases/2/app/Http/Controllers/TelegramController.php(75): App\\Http\\Controllers\\TelegramController->parseMessage(Object(TelegramBot\\Api\\Types\\Message), '{\"update_id\":88...')\n#7 [internal function]: App\\Http\\Controllers\\TelegramController->newhook()\n#8 /var/www/telegram/releases/2/bootstrap/cache/compiled.php(9424): call_user_func_array(Array, Array)\n#9 /var/www/telegram/releases/2/bootstrap/cache/compiled.php(9486): Illuminate\\Routing\\Controller->callAction('newhook', Array)\n#10 /var/www/telegram/releases/2/bootstrap/cache/compiled.php(9466): Illuminate\\Routing\\ControllerDispatcher->call(Object(App\\Http\\Controllers\\TelegramController), Object(Illuminate\\Routing\\Route), 'newhook')\n#11 [internal function]: Illuminate\\Routing\\ControllerDispatcher->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#12 /var/www/telegram/releases/2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))\n#13 [internal function]: Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#14 /var/www/telegram/releases/2/bootstrap/cache/compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))\n#15 /var/www/telegram/releases/2/bootstrap/cache/compiled.php(9467): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))\n#16 /var/www/telegram/releases/2/bootstrap/cache/compiled.php(9454): Illuminate\\Routing\\ControllerDispatcher->callWithinStack(Object(App\\Http\\Controllers\\TelegramController), Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request), 'newhook')\n#17 /var/www/telegram/releases/2/bootstrap/cache/compiled.php(8524): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request), 'App\\\\Http\\\\Contro...', 'newhook')\n#18 /var/www/telegram/releases/2/bootstrap/cache/compiled.php(8511): Illuminate\\Routing\\Route->runController(Object(Illuminate\\Http\\Request))\n#19 /var/www/telegram/releases/2/bootstrap/cache/compiled.php(8225): Illuminate\\Routing\\Route->run(Object(Illuminate\\Http\\Request))\n#20 [internal function]: Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#21 /var/www/telegram/releases/2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))\n#22 [internal function]: Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#23 /var/www/telegram/releases/2/bootstrap/cache/compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))\n#24 /var/www/telegram/releases/2/bootstrap/cache/compiled.php(8226): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))\n#25 /var/www/telegram/releases/2/bootstrap/cache/compiled.php(8217): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#26 /var/www/telegram/releases/2/bootstrap/cache/compiled.php(8207): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))\n#27 /var/www/telegram/releases/2/bootstrap/cache/compiled.php(2419): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))\n#28 [internal function]: Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))\n#29 /var/www/telegram/releases/2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))\n#30 /var/www/telegram/releases/2/bootstrap/cache/compiled.php(3286): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#31 [internal function]: Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#32 /var/www/telegram/releases/2/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)\n#33 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#34 /var/www/telegram/releases/2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))\n#35 [internal function]: Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#36 /var/www/telegram/releases/2/bootstrap/cache/compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))\n#37 /var/www/telegram/releases/2/bootstrap/cache/compiled.php(2366): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))\n#38 /var/www/telegram/releases/2/bootstrap/cache/compiled.php(2350): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))\n#39 /var/www/telegram/releases/2/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))\n#40 {main}"] 
```

**Comment by akeinhell** [comment]
fixed in #8
